src/docs/index.ts, src/primitives.ts
Used to track sentiment on the *docs* page
=> fix: sentiment tracking analytics

.github/pull_request_template.md, .github/workflows/check-pr-title.yaml, README.md, package.json, scripts/install-in-repo.sh
This PR adds documentation and both manual and automated processes for adding new events to standardize across all usages.
- Comprehensive naming and organization guide in README
- convenience scripting for testing across repositories
- Enforces PR title conforming
- Added PR template
- Ran with Uniswap/docs and Uniswap/interface
=> ci: event definition rules + testing and automation

README.md, src/interface/index.ts
we're adding one new type of tile to the about page - a link to the fiat-on-ramp
...
add a new ElementName
- 
tested locally using the test script, verified that the ElementName is available from the package.
=> feat: buy crypto about tile element

src/interface/events.ts, src/interface/properties.ts
so we can add trm analytics to amplitude
=> feat: add risk check events

src/nft/events.ts
Adding the appropriate events for the new pay with any token feature on the nft side
=> feat: nft pay with any token events

src/primitives.ts
https://uniswaplabs.atlassian.net/browse/WEB-2879?atlOrigin=eyJpIjoiNGQ5YTRhMWU5MTY1NDM0YmIxNmJkNTdhMDM4OTcwNjUiLCJwIjoiaiJ9
add `PEER_WALLET_NAME` to this enum for use in `interface`
=> feat: CustomUserProperties Peer Wallet Name

src/interface/events.ts, src/interface/trace.ts
https://www.notion.so/uniswaplabs/Mini-Portfolio-Main-Doc-product-spec-b5e26c04c05b40c4ac4f5c61b3248893?pvs=4#71da8f8415824be598c7fed5bcc571b6
=> feat: mini portfolio events

src/interface/events.ts, src/interface/trace.ts
Adds analytics for interactions with the Mobile-Wallet-specific UI within Interface.
Adds four new entries to the `InterfaceEventName` enum
=> feat: add interface analytics events for mobile go to market

src/primitives.ts
https://uniswaplabs.atlassian.net/browse/WEB-3112
=> feat: add referrer user property

src/primitives.ts
We want to start logging the user's router preference as a custom user property.
=> feat: add router preference to custom user properties

src/interface/events.ts
https://linear.app/uniswap/issue/WEB-2660/log-chain-changed-events
-  add CHAIN_CHANGED event to `InterfaceEventName`
👀
=> feat: add chain_changed event

src/interface/trace.ts
Adding element for this app download button: <img width="311" alt="Screenshot 2023-11-07 at 11 49 58 AM" src="https://github.com/Uniswap/analytics-events/assets/27475332/140671dd-8255-4939-9f45-824d0d4041e4">
=> feat: add navbar menu app download element

src/interface/trace.ts
sorry last one!! Missed the landing page download button
=> feat: add landing page app download button element

src/primitives.ts
Adding to support analytics opt out for wallet and standardize events across with web!
- Adds two new primitive events
=> feat: add toggle and heartbeat events

src/interface/trace.ts
* Adding new Pool details page for .info project
=> feat: add Pool Details Page to InterfacePageName

src/primitives.ts
Adding this to ensure acceptance of terms is captured through any product in a standardized event
- Add TOS primitive event
=> feat(MOB): Add TOS event

.github/workflows/release.yaml
Follows the new npm deploy process in https://www.notion.so/uniswaplabs/Secure-NPM-Deploys-bb4c1b433c344e3aa3e041f028c74b91 
Moved the deploy job to the Release environment and now loads secrets from our  1pass vault
=> chore: added the new npm deploy flow

.github/workflows/release.yaml
Fixes on top of #71 to use the autogenerated github token
=> fix(ci): fix github secret and remove unused secret

.github/workflows/release.yaml
Moves our deploy to the new npm runner (makes it faster and more secure)
=> chore(infra): add the npm runner token

src/interface/events.ts
We want to track the language the user selected
...
- Adds the following events:
- LANGUAGE_SELECTED
=> feat(web): add language selected event

src/primitives.ts
This is to force a release so #79 gets released
=> feat: forcing a release 

.github/workflows/release.yaml, package.json
Adds provenance to the npm deploy
=> chore(infra): add provenance

.github/workflows/release.yaml
Sets up write permissions for the deploy action
=> chore(infra): write permissions to the repo

src/swap/events.ts, src/swap/properties.ts
WEB-4928
Add tracking around swap price impact acknowledgement 
- Adds `SWAP_PRICE_IMPACT_ACKNOWLEDGED`
=> feat(web): add price impact events

src/interface/trace.ts
Adds astro modal to interface modal names
=> feat(web): add astro modal

src/liquidity-positions/properties.ts
I know we are trying to deprecate this repo but figured it's cleaner to update this type here than to create a `FeePoolSelectActionLocal` in monorepo lol, at least until we fully migrate this repo over
=> feat: add fee pool select action for new v4 lp flows

src/liquidity-positions/events.ts
Adds an event for tracking when user modifies amounts in wallet.
-
=> feat(web): add lp tx mod in wallet event

src/primitives.ts
we need to add testnet mode in the custom user properties for web
=> feat(web): adding testnet mode
